M48
; DRILL file {KiCad (6.0.7)} date Fri Aug  5 22:04:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T22:04:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X5.4321Y-5.5094
X5.623Y-5.5094
T2
X3.1713Y-5.3232
X3.1713Y-5.5594
X4.0965Y-5.3232
X4.0965Y-5.5594
T3
X5.4203Y-5.6287
X5.6348Y-5.6287
T0
M30
